### ISSUE TITLE
Problems facing in version 1.0 

### ISSUE THREAD

**Issue by jainshravan123** [andywer/threads.js#129]
I'm facing following issue if i use 1.0 version of threads module. 

1. I was able to see the documentation related to pool few days back but now it's not coming. 
2. If i create the more than 2 threads then it's not able to run the worker in cloud. 
```
let { spawn, Pool, Worker } = require('threads')
const pool = Pool(() => spawn(new Worker('./myworker')), 1)
```
Following is myworker.js

```
let { expose } = require('threads')
const Promise = require('bluebird')

expose(function add (results) {
  return new Promise((resolve) => {
    resolve({'success' : true})
  })
})

```

And i'm putting into the queue as following.

```
pool.queue((multiplier) => {
              multiplier(batch).then((data) => {
                console.log('Coming here 3 :', data)
             })
})
```

@andywer Can you please help me in fixing these issues?

**Comment by andywer** [comment]
Hi @jainshravan123!

> 1. I was able to see the documentation related to pool few days back but now it's not coming.

Do you mean jsdoc documentation, like the one that you see in your IDE? Otherwise the documentation is here: <https://threads.js.org/usage#thread-pool>

> 2. If i create the more than 2 threads then it's not able to run the worker in cloud.

What's the error?

**Comment by jainshravan123** [comment]
@andywer The problem which i'm facing during second point is that code is getting stuck just before `pool.queue`. It's not going inside the worker at all. And callback inside the pool.queue is getting called. 

And why the documentation has been removed from the top i.e. https://www.npmjs.com/package/threads

**Comment by andywer** [comment]
Can you provide some sample code? I assume it's just used in a wrong way, but that would also mean we have to improve the documentation or even change the API if it's not obvious.

> And why the documentation has been removed from the top

What information has been removed from the top of the readme that you expected there? I am not sure what you are referring to.

Do you mean why the pool documentation is not in the readme anymore, but only the link to the website?

**Comment by jainshravan123** [comment]
Yes @andywer. I'm talking about the pool documentation only. It's not there in readme of threads module. 

And Following the sample code

sampleThread.js
<img width="485" alt="Screen Shot 2019-07-01 at 12 51 28 PM" src="https://user-images.githubusercontent.com/6860473/60417844-10a93080-9bff-11e9-9255-1e246db50ac2.png">

myworker.js
<img width="310" alt="Screen Shot 2019-07-01 at 12 51 37 PM" src="https://user-images.githubusercontent.com/6860473/60417883-2585c400-9bff-11e9-8fc5-d84f8e224832.png">


So if i run this code(sampleThread.js) then it comes to line number(#4 of sampleThread.js) and after executing the line number(#5 of sampleThread.js) it should run the worker but sometimes it does not go inside the myworker.js at all. 

Thanks @andywer for helping me.

**Comment by andywer** [comment]
Alright - this is something we can work with 👍

Regarding the sample code:

I spot one issue that might or might not be related to your problem: You do not `return` the `multiplier.batch().then()`. I would advise you to use modern `async`/`await` syntax as those things are easy to miss when handling promises manually.

Not sure if this is causing your issue, though. Let me know 😉

---

Regarding the documentation:

All the detailed documentation has been moved to the website, since it's easier to show a lot of information there, as we can have multiple levels of navigation, like the side navigation, the top menu, ...

Otherwise it will be really hard to find things in a large readme file, esp. if we keep adding functionality.

I hear your concern, though. Would it help if there was not only a link to the website in the readme, but also quick links to `Getting started`, `Basics`, `Pool`, ...?

**Comment by jaliph** [comment]
I'm not having the a nice feeling about this upgrade. We are able to see performance drop if compared to v0. FYI, we are using tiny workers as we are still on node 8. 

Also, We are able to see the Code getting stuck like @jainshravan123 mentioned. I don't think using async/await might help. Using async/await will require code changes to the whole calling stack.

I believe better examples in Read Me might help.

**Comment by jainshravan123** [comment]
@andywer I have tried to return the `multiplier.batch().then()` but it also did not solve the problem. 
The performance is very very slow if i use version 1 of this module in comparison of version `0.12.1`. 

cc: @jaliph

**Comment by andywer** [comment]
@jaliph @jainshravan123 **I will look into the "getting stuck" and performance issues tonight. Those are of course major concerns.**

Btw, what operating system are you using (where you see the declined performance)?

Feel free to keep v0.12 running in production until v1.0 leaves the beta state. Just be aware that the old API was very hard to maintain and unintuitive to use, so we very much needed to switch to the new API.

The suggestion to use modern day `async`/`await` was purely to prevent things like the missing `return`. It won't help if there are deeper performance issues, of course.

There is a fair chance that `tiny-worker` is slower than the old implementation. Since starting from node 10 you can use `worker_threads` (with a feature flag and in node 12 without) and since node 8 will reach its end of life in less than half a year, consider the `tiny-worker` to be just a temporary fix.

> I believe better examples in Read Me might help.

Since this is an open source project, feel free to open PRs or suggest changes 😉

I just want to highlight that this is a project I am doing in my spare time and it's offered free of charge. Contributions are therefore, as always, very welcome.

It would for example help a lot if you can gather some more details about where the time is spent if you see a performance decline. If you are using the library for commercial purposes, a small donation would also be a great alternative to contribute (I just added that new GitHub "Sponsor" button to the project).

It is all voluntary of course, but every contribution helps to strengthen and improve the project. At the end of the day it is a community effort 🙂

**Comment by andywer** [comment]
I just created a simple benchmark:

Use bcrypt (10 salting rounds, pure JS implementation `bcryptjs`) to hash 500 random 16 character long strings using a thread pool of 8 threads on a MacBook Pro with 8 cores. Two implementations - one using threads.js v0.12 and one using threads.js v1.0.0-beta.1.

Result:
v0.12 on node 8.7: ~8.85s
v1.0 beta on node 8.7: ~9.28s

So v1.0 is a bit slower, but not by much. Since it hasn't been optimized for speed so far, I'm pretty sure we will be able to come even closer to v0.12 performance in the future.

**Comment by andywer** [comment]
What's the status here?

You haven't shared yet what operating system you are using. The declined performance might be some Windows-specific bug, for instance.

**Comment by andywer** [comment]
Closing, due to lack of response. Feel free to re-open.
