### ISSUE TITLE
Returning an array from thread

### ISSUE THREAD

**Issue by dy** [andywer/threads.js#15]
Hi @andywer!

An issue actually related with https://github.com/audreyt/node-webworker-threads/issues/99.
I tried both [webworker-threads](https://npmjs.org/package/webworker-threads) and [threads](https://npmjs.org/package/threads) libs to implement multithreading in [nogl-shader-output](https://npmjs.org/package/nogl-shader-output), and both packages get very slow at returning an array from threads. It takes 800ms on my laptop to return 300×300 array from the thread.

Whether something I don’t know or is there a way to speed things up?

Thank you.

**Comment by andywer** [comment]
Hey Deema!

Did you use https://github.com/andywer/threads.js#transferable-objects? Passing large arrays is by default very slow, since the whole array is copied when sending messages between the threads. But you can explicitly transfer the ownership of an array to the other thread when sending data to it (see link). This is much faster, but the sending thread cannot access the array anymore until the other thread gives the array ownership back.

**Comment by andywer** [comment]
I forgot to ask: Are you working in a browser or a node.js setting?

**Comment by dfcreative** [comment]
@andywer in node.

**Comment by andywer** [comment]
Yeah, my suggested approach was also browser-related... I don't have a Node.js solution by hand right now. The best I could come up with when googling it was this: https://github.com/audreyt/node-webworker-threads/issues/58

But that issue seems quite dead...

**Comment by andywer** [comment]
Closing for now.

This is a rather tough one. Might be easy to fix once node supports web workers (nodejs/node#13143).
