### ISSUE TITLE
Question: Memory constraints of worker processes

### ISSUE THREAD

**Issue by philkunz** [andywer/threads.js#165]
Is there a proper way to do --max_old_space_size with worker threads?

**Comment by andywer** [comment]
Not as of now, I think - not sure if it actually works out-of-the-box yet, though. Are we talking tiny-worker or native worker_threads?

The other question is what to set that value to. I suppose just passing the setting on to the worker process - so that each process (master + workers) may consume max_old_space_size each.

**Comment by andywer** [comment]
It should be easy to extend tiny-worker to pass that CLI option to the child process. Not sure if the native worker threads do something like that by default already.

**Comment by andywer** [comment]
Just realized: It might not be possible to set this value for worker threads at all. See <https://nodejs.org/api/worker_threads.html#worker_threads_new_worker_filename_options>.

> execArgv <string[]> List of node CLI options passed to the worker. V8 options (such as --max-old-space-size) and options that affect the process (such as --title) are not supported.
