### ISSUE TITLE
pool max queued jobs setting

### ISSUE THREAD

**Issue by cmonacaps** [andywer/threads.js#172]
Can a max queue length be added to the pool options?  It would need to come along with a potentially blocking or awaitable and a fail-fast-when-full enqueue.  Perhaps the contract of the existing `queue` method can be met by the fail-fast version - if the pool were constructed with the `maxQueueLength` option, then `queue` would either throw or return negative status if the maximum number of jobs had already been queued.

On the other hand is it true that an arbitrary number of jobs could be still be waiting, while enqueueing to the fixed-length pool, using an awaitable enqueue method, and waiting on the pool's full condition?  If so perhaps then a blocking enqueue.

**Comment by andywer** [comment]
Hi! What's your use case? Not 100% sure yet if this is a need that more users have.

You can already build such a queue yourself, on top of today’s `Pool`. I think it does not expose it's current queue, but you could have a "pending tasks" counter and use `pool.events()` to increment/decrement it whenever a task is queued/unqueued. Then just throw on queueing if the counter is already at max.

**Comment by andywer** [comment]
Fair enough. So bottom line there are two open questions, I think:

- What would `maxQueueLength` default to? (10000? infinity?)
- Should we really provide two `queue()` methods - one awaitable and one fail-fast - or should we only fail-fast?

Regarding the latter question, I tend towards making the existing `queue()` method fail-fast as it's simple (for the user and simple to implement).

But we would then need to provide a backpressuring awaitable one then, too, I guess, in order to cover all use cases.

**Comment by cmonacaps** [comment]
Hi, sorry I missed the update.  I think it's almost not possible to define a good default in the framework since it's so heavily application-dependent.  In practice the ideal queue length would be just large enough to periodically return to empty during the application lifetime.  It becomes a key tunable parameter in the application.

Otoh I agree, I think with the fail-fast dequeue you can do whatever you want, and not the case for a blocking dequeue, so to trim down the API you would only need that one.

**Comment by andywer** [comment]
Hey @cmonacaps. Check out #188 and feel free to share some feedback on it if you've got some time.
