### ISSUE TITLE
isWorkerRuntime() === true for all browser windows

### ISSUE THREAD

**Issue by barretron** [andywer/threads.js#242]
I noticed that threads.js was adding `uncaughtException` and `unhandledRejection` handlers to the page, so I peeked at the code and noticed that `isWorkerRuntime()` was returning `true` for the browser window.

```ts
const isWorkerRuntime: AbstractedWorkerAPI["isWorkerRuntime"] = function isWorkerRuntime() {
  return typeof self !== "undefined" && self.postMessage ? true : false
}
```

AFAICT, browser windows have both a `self` global (`self === window`) and a `self.postMessage` function.

**Comment by andywer** [comment]
Thanks for pointing out, @barretron! I almost forgot about this issue…

Background story: While working on #228 I already stumbled upon and fixed it on that feature branch. Now the PR is still not merged because of some weird issues I was facing in this PR.

I will port the fix from #228 to a new PR!
