### ISSUE TITLE
How can I tell if module worker has terminated/died?

### ISSUE THREAD

**Issue by strogonoff** [andywer/threads.js#281]
I am creating a worker and assigning it to private class property in main thread.

The property is of type `Worker | null` (or rather apparently `ArbitraryThreadType | null`). It is `null` when class is constructed, then the non-null type once I initialize it (since async initialization is not possible in class constructors).

If my worker gets terminated, will the property be of type `null` again, or is there another way to check if the worker is still running? If there’s no way to check, do I need to listen to certain events and handle this on my app level?

**Comment by andywer** [comment]
Hey @strogonoff.

No, the worker reference will not become `null`. You can, however, subscribe to the [worker's events](https://threads.js.org/usage-advanced#thread-events) in order to handle termination.

Not sure if you really need that, though. If the worker is private, then only your class can terminate the worker and you can just handle the worker termination in the moment you terminate it 😉

**Comment by strogonoff** [comment]
@andywer 

> If the worker is private, then only your class can terminate the worker

I wish the worker could only terminate with my consent, but unhandled termination is always a problem ;)

**Comment by andywer** [comment]
Fair enough. But beware: The behavior differs between web workers and node worker threads.

If a worker thread errors, it's terminated. If a web worker errors, it's still up and running.

**Comment by strogonoff** [comment]
Got it. In my case, it’s node—I recall reading from `worker_threads` that it’ll be terminated. That‘s why the worry!
