### ISSUE TITLE
ElectronJS BrowserWindow is not a constructor

### ISSUE THREAD

**Issue by Brouilles** [andywer/threads.js#403]
Here my worker: 
```
const { expose } = require('threads/worker');
const { BrowserWindow } = require('electron');
const fs = require('fs');
const log = require('electron-log');
const { URLSearchParams } = require('url');

const pdfOptions = {
    marginsType: 1,
    pageSize: 'A4',
    printBackground: true,
    printSelectionOnly: false,
    landscape: false
};

expose({
    generate(webpackEntry, preload, filePath, id, type) {
        let win = new BrowserWindow({
            show: false,
            webPreferences: {
                preload
            }
        });
          
        win.loadURL(webpackEntry + `?${new URLSearchParams({id, type})}`);

        win.webContents.on('did-finish-load', async () => {
            win.webContents.printToPDF(pdfOptions).then(data => {
                fs.writeFile(filePath, data, function (err) {
                    if (err) {
                        log.error(err);
                    } else {
                        log.info('PDF Generated Successfully');
                        // event.sender.send('onPDFGeneratedResponse', path.basename(filePath));
                    }
        
                    win.close();
                    win = null;
                    // shell.openExternal(filePath);
                });
            }).catch(error => {
                log.error(error)
                win.close();
                win = null;
            });
        });
    }
});
```

Seems because at the spawn, it used `node ./printToPDF.js` and not `electron ./printToPDF.js` to start the worker. A way to change this?

**Comment by Brouilles** [comment]
I have also tried to setup the window in the main thread and pass the id in parameter. But `BrowserWindow.fromId` return an error, `BrowserWindow` is undefined.

**Comment by andywer** [comment]
Hi @Brouilles!

I assume you spawned a node worker thread out of node.js code, nota web worker from inside a browser window.

Since I haven't actively been using threads.js in electron (at least not outside the web view), this is somewhat speculative, but I believe there is no better way to do that here as AFAICT there is no custom electron-focussed worker_threads implementation, you will always just use the off-the-shelf node.js worker_threads from which you cannot import anything `electron` as these things reside in a different thread.

So what I would propose is to only import from and use `electron` in the main thread, keep all the related code in the main thread and only let the workers report what needs to be done electron-wise to the main thread by returning an observable that will emit events that the main thread then reacts to.

I strongly doubt there is any chance to use the `electron` module directly in the workers as it pretty certainly consists of single-threaded code.

**Comment by Brouilles** [comment]
Thanks for your answer.
