### ISSUE TITLE
killAll does not terminate threads but stays idling?

### ISSUE THREAD

**Issue by devboxr** [andywer/threads.js#60]
Just playing around to see if this library is something I could use and I like it!

I do however have an issue with the code below, I tried to keep it as simple as possible.

```js
const threadPool = new Pool();

for (const letter of ['a', 'b', 'c']) {
  threadPool.run((params, message) => {
    message(`The letter was: ${letter}`);
  }).send({ letter });
}

threadPool
  .on('done', (job, message) => {
    console.log('Job done:', job);
  })
  .on('error', (job, error) => {
    console.error('Job errored:', job);
  })
  .on('finished', () => {
    console.log('Everything done, shutting down the thread pool.');
    threadPool.killAll();
  });
```

**Outputs:**

```shell
$ node index.js
Job done: The letter was: a
Job done: The letter was: b
Job done: The letter was: c
Everything done, shutting down the thread pool.
```

However, the `threadPool.killAll();` doesn't seem to to anything as the console stays idling?

![image](https://user-images.githubusercontent.com/16515780/29497105-09cbe16e-85da-11e7-8892-87e90336ed7e.png)

Am I doing this wrong?

Environment is Mac OS Sierra with node v8.3.0.

Thanks!

**Comment by andywer** [comment]
Hey @devboxr. Thanks for submitting the issue!

No, I don't think you are doing anything wrong. Code looks fine. But I also don't think that the `.killAll()` does nothing. It will shut down the workers, but probably there is some async callback somewhere that doesn't get cancelled. Freakin' event emitters... 🙈

I already created an issue with a basic roadmap for a 1.0 version #54 that uses observables rather than event emitters to avoid those issues. Not sure when I get to finally implement that, though 🙃

**Comment by andywer** [comment]
v1.0 beta is here with a whole new API. Closing.
