### ISSUE TITLE
Passing functions through pool.send([]) is consistently failing.

### ISSUE THREAD

**Issue by ZenModeRy** [andywer/threads.js#69]
I've been banging my head for a while, and at this point, I honestly have no idea what's going on or how to fix it. I'm using Node 8.5 on Mac OSX. I've verified that the worker is loading properly. Every aspect of this module works for me except this one piece. Any thoughts? 

**THREADER.JS**
```
module.exports.setup = async worker =>
{
    const threads = require('threads');
    const pool = new threads.Pool();
    pool.run(worker);
    let someFunction = (async foo =>
    {
         return foo;
    });
    const job = await pool.send([someFunction, 'bar']);
}
```

**WORKER.JS**
```
module.exports = async(input, done) =>
{
    const [theFunction, theArg] = input;
    console.log(theFunction(theArg)); // Fails with: theFunction is not a function
}
```

**Comment by andywer** [comment]
Yeah, passing functions to workers is virtually impossible, since we would need to serialize and deserialize the functions. Could work with pure functions, though. As soon as you reference any identifier that was defined outside the function, it would crash.

Don't know if it's worth to add the feature if it will break in most cases with a hard-to-understand error, anyway.

But we could definitely mention the limitation in the docs 😉

**Comment by ZenModeRy** [comment]
Awesome response. I think mentioning the limitation could be hugely helpful for others, as I went down a rabbit hole for days on this one haha. Thanks again!!!
