### ISSUE TITLE
Share imports between runners

### ISSUE THREAD

**Issue by ArielGueta** [andywer/threads.js#70]
Hey,

First of all thanks for this great library. 

Let's say I need to run a pool with different runners but they share the same imports, for example: 

```
  pool.run((input, done) => {
        importScripts('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js');
        ....process one
        done(input);
      }
    ).send({data: 1});
```

```
 pool.run((input, done) => {
        importScripts('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js');
        ... process two
        done(input);
      }
    ).send({data: 2});
```

In this case, the browser will download the moment library twice, how can I overcome this problem? thanks!

**Comment by andywer** [comment]
Thanks for the kind words :)

This behavior originates from the browser itself and should be fine, since the browser should load the file from cache when run the second time.

Do you experience performance issues? A work-around for this behavior could be implemented at lib level, though.

If there‘s an issue, I‘d guess the file’s caching headers are misconfigured or the „disable cache“ switch in the dev tools is set 😉

**Comment by ArielGueta** [comment]
Thanks!
