### ISSUE TITLE
How can I past another module to thread body?

### ISSUE THREAD

**Issue by DmitryGG** [andywer/threads.js#80]
I mean how can we past some module to thread? There are any solutions?

```
const axios = require('axios')
const spawn = require('threads').spawn

const url = '...'

const thread = spawn(async ({ games, axios, url }, done) => {
  let gamesVideos = []

  console.log({ games, axios, url }) // OUTPUT OF THIS BELOW

  for (const { _id } of games) {
    const gameVideos = (await axios(`${url}/${_id}`)).data.videos
    gamesVideos.push(gameVideos)
  }

  done(gamesVideos)
});

Promise.resolve()
  .then(async () => {
    const games = (await axios.get(url)).data

    // console.log(games.slice(0, 10))

    thread
      .send({ games, axios, url })
      .on('message', res => {
        console.log('message:', res);
      })
      .on('error', error => {
        console.error('Worker errored:', error);
      })
      .on('exit', () => {
        console.log('Worker has been terminated.');
      });
  })
  .catch(err => console.error('[App]', err))
```

Output of `console.log({ games, axios, url })`:
```
{ games:
  [
    {},{}...
  ],
  axios: undefined, // why undefined here?
  url: '...' }
```

**Comment by andywer** [comment]
Hey @DmitryGG.

Yeah, the docs are rather sparse. It seems a bit strange to me too that `axios` is `undefined`, but it is normal that you cannot pass such complex objects with methods, since node / your browser need to serialize and deserialize it when sending it to the thread in a message.

So what you can do to use `axios` in the thread:
- in node: just use `require('axios')` in the thread
- in browser: use `importScript('https://unpkg.com/axios/dist/axios.min.js')` to load the bundled axios script. `axios` should then be available in the worker as if you had a `<script src="https://unpkg.com/axios/dist/axios.min.js"></script>`

Hope that helps.

Closing the issue for now. Feel free to re-open if something doesn't work.

**Comment by DmitryGG** [comment]
Yep, this works:

```js
const axios = require('axios')
const spawn = require('threads').spawn

const thread = spawn((input, done) => {
  const axios = require('axios')
  ...
})
```

Thanks for quick answer!
