### ISSUE TITLE
use without node.js??

### ISSUE THREAD

**Issue by WorkMAE** [andywer/threads.js#83]
I am unable to install node js due to corporate limitations, is there a way to use this without having to install node.js?

I included the script reference in the index.html page but when I try and reference it like this:

const spawn = threads.spawn I get "ReferenceError: threads in  not defined"

How can I make this work without node js?  You should probably have some examples of this, FYI...all the examples are using node.js and not everyone can use this.

**Comment by andywer** [comment]
Hey @WorkMAE. Looks like its not `threads`, not `thread`. Don‘t ask me why, but I suppose there are barely any users out there using the `<script>` tag, so no one complained yet...

I can change it to `threads`, though, which seems way more intuitive. Will also add this information to the readme!

**Comment by WorkMAE** [comment]
Thanks, but I also tried "thread" and got the same error...anything else I can look at?  Is this being included on the global scope?  I am using angularJS do I need to do any type of DI?

**Comment by WorkMAE** [comment]
@andywer Also, does this support TRansferable Objects such as ArrayBuffers?  I am wanting to use this to do work on files I am loading as binary files and wanting to pass the ArrayBuffer or Uint8Array(if I need to convert first) to the thread for it do the extra processing work to turn it into a useable JSON object...as I am using this for importing YTD data, each month has it's own file and as such, the further into the year we go, the more data I will be loading and needing to have processing...

I am hoping this usage is possible as I am trying to use some other threading libraries and cannot get this to work properly...

**Comment by andywer** [comment]
Yeah, all features should also be available when using the UMD bundle. The code is the same, it's just dressed in another jacket 😉

**Comment by WorkMAE** [comment]
@andywer Awesome! Is there an example of link to how to use the UMD Bundling properly?

**Comment by andywer** [comment]
@WorkMAE You can take a look at the [updated readme in the PR](https://github.com/andywer/threads.js/blob/88a7aea931c6b95522c27cd9b839c2945e85f694/README.md#script-tag).

It's not published yet, though. And I can't merge and publish right now, since the build is suddenly broken 🙃

Might be an issue with Travis CI, not sure...

**Comment by WorkMAE** [comment]
@andywer Unless I am missing something, I don't see anything related to plain JS usage...I still see everything using node.js...unless the comment about not being published yet was related to the readme...

**Comment by andywer** [comment]
> The library will be exposed on the global window scope as threads.

This is all information you need to use it, I hope. Since the UMD bundle was broken for at least a year and no one ever complained, I would say that you are pretty much the only user still using `<script>` inclusion right now.

So changing the examples or providing more examples for UMD doesn't seem worth the effort. Especially since there are no differences in usage. Just drop the `import threads from ...` line and just use the `threads` global.

**Comment by WorkMAE** [comment]
@andywer trust me I would LOVE to use node.js but I can't due to ridiculous proxy limitations at work...
